apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: codx
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  config.yaml: |
    instanceName: {{ include "common.names.fullname" . }}
    namespace: {{ .Release.Namespace }}
    http:
      listenAddr: {{ .Values.http.listenAddr | quote }}
      tlsCertFile: {{ .Values.http.tlsCertFile | quote }}
      tlsKeyFile: {{ .Values.http.tlsKeyFile | quote }}
    oidc:
      issuer: {{ .Values.oidc.issuer | quote }}
      clientId: {{ .Values.oidc.clientId | quote }}
      redirectUrl: "https://{{ .Values.ingress.hostname }}/auth/callback"
      groupClaimName: {{ .Values.oidc.groupClaimName | quote }}
      adminGroup: {{ .Values.oidc.adminGroup | quote }}
      usernameClaimName: {{ .Values.oidc.usernameClaimName | quote }}
    redis:
      host: {{ template "common.names.fullname" . }}-valkey.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:6379
      db: {{ .Values.redis.db }}
      {{- if .Values.redis.tls }}
      tls: true
      {{- end }}
      {{- if .Values.redis.caFilePath }}
      caFilePath: {{ .Values.redis.caFilePath | quote }}
      {{- end }}
    certManager:
      issuerType: {{ .Values.tls.issuerRef.kind | quote }}
      issuerGroup: {{ .Values.tls.issuerRef.group | quote }}
      issuerName: {{ include "codx.issuerName" . }}
      renewal: {{ .Values.certManager.renewal | quote }}
      validity: {{ .Values.certManager.validity | quote }}
    tls:
      serverCertDir: {{ .Values.tls.serverCertDir | quote }}
      clientCertDir: {{ .Values.tls.clientCertDir | quote }}
      caDir: {{ .Values.tls.caDir | quote }}
    slug:
      usernameField: {{ .Values.slug.usernameField | quote }}
      maxLength: {{ .Values.slug.maxLength }}
    inactivity:
      signal: {{ .Values.inactivity.signal | quote }}
      checkInterval: {{ .Values.inactivity.checkInterval | quote }}
    workspaceService:
      {{- if .Values.workspaceService.annotations }}
      annotations:
        {{- toYaml .Values.workspaceService.annotations | nindent 8 }}
      {{- end }}
      ipFamilies: {{ toYaml .Values.workspaceService.ipFamilies | nindent 8 }}
      ipFamilyPolicy: {{ .Values.workspaceService.ipFamilyPolicy | quote }}
