{{- if .Values.oidc.clientSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codx.fullname" . }}-oidc
  labels:
    {{- include "codx.labels" . | nindent 4 }}
type: Opaque
stringData:
  clientSecret: {{ .Values.oidc.clientSecret | quote }}
{{- end }}
{{- if .Values.redis.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codx.fullname" . }}-redis
  labels:
    {{- include "codx.labels" . | nindent 4 }}
type: Opaque
stringData:
  redisPassword: {{ .Values.redis.password | quote }}
{{- end -}}
