apiVersion: v1
kind: Service
metadata:
  name: {{ include "codx.fullname" . }}
  labels:
    {{- include "codx.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 8443
      targetPort: https
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "codx.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: server
